version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: app_frontend
    depends_on:
      - backend
    networks:
      - mongo-data

  backend:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3004:3004"
    environment:
      - SEVER_PORT=3004
      - MONGODB_URI=mongodb://root:example@mongodb:27017/fs-a1
    depends_on:
      - mongodb
    networks:
      - mongo-data

  mongodb:
    container_name: mongodb-fs
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example # Use a secure password in production
    volumes:
      - ./mongodb/mongo-data:/data/db
      - ./mongodb/init/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27018:27017"
    networks:
      - mongo-data

networks:
  mongo-data:
    driver: bridge

